version: 2.1

orbs:
  python: circleci/python@0.2.1
  browser-tools: circleci/browser-tools@1.0.0

jobs:
 test:
  docker:
      - image: 'cimg/node:13.12'
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - browser-tools/install-browser-tools
      - run:
          command: python wms_test.py
          name: wms_test.py

workflows:
  main:
    jobs:
      -test
