version: 2.1

orbs:
  python: circleci/python@0.2.1
  browser-tools: circleci/browser-tools@1.0.0

jobs:
  build-and-test:
    executor: python/default
    parameters:
      replace-existing:
        type: boolean
        default: false
        description: >
          If there is an existing installation of Google Chrome, replace it
          with the latest stable release?
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          name: Install Google Chrome
          command: |
            if [[ $EUID == 0 ]]; then export SUDO=""; else export SUDO="sudo"; fi
                    # installation check
                    if uname -a | grep Darwin > /dev/null 2>&1; then
                      if ls /Applications | grep "Google Chrome" > /dev/null 2>&1; then
                        <<#parameters.replace-existing>>echo "$(/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --version)is currently installed; replacing it"
                        HOMEBREW_NO_AUTO_UPDATE=1 brew cask uninstall google-chrome > /dev/null 2>&1 || true
                        $SUDO rm -rf /Applications/Google\ Chrome.app > /dev/null 2>&1 || true<</parameters.replace-existing>><<^parameters.replace-existing>>echo "$(/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --version)is already installed"
                        exit 0<</parameters.replace-existing>>
                      else
                          echo "Google Chrome is not currently installed; installing it"
                      fi
                    elif cat /etc/issue | grep Alpine > /dev/null 2>&1; then
                      if command -v chromium-browser > /dev/null 2>&1; then
                        <<#parameters.replace-existing>>echo "$(chromium-browser --version)is currently installed; replacing it"
                        $SUDO apk del --force-broken-world chromium > /dev/null 2>&1 || true
                        $SUDO rm -f "$(command -v chromium-browser)" > /dev/null 2>&1 || true<</parameters.replace-existing>><<^parameters.replace-existing>>echo "$(chromium-browser --version)is already installed to $(which chromium-browser)"
                        exit 0<</parameters.replace-existing>>
                      else
                        echo "Google Chrome (via Chromium) is not currently installed; installing it"
                      fi
                    elif command -v yum > /dev/null 2>&1; then
                      if command -v google-chrome > /dev/null 2>&1; then
                        <<#parameters.replace-existing>>echo "$(google-chrome --version)is currently installed; replacing it"
                        $SUDO yum remove -y google-chrome-stable > /dev/null 2>&1 || true
                        $SUDO rm -f "$(command -v google-chrome)" > /dev/null 2>&1 || true<</parameters.replace-existing>><<^parameters.replace-existing>>echo "$(google-chrome --version)is already installed to $(which google-chrome)"
                        exit 0<</parameters.replace-existing>>
                      else
                        echo "Google Chrome is not currently installed; installing it"
                      fi
                    else
                      if command -v google-chrome > /dev/null 2>&1; then
                        <<#parameters.replace-existing>>echo "$(google-chrome --version)is currently installed; replacing it"
                        $SUDO apt-get -y --purge remove google-chrome-stable > /dev/null 2>&1 || true
                        $SUDO rm -f "$(command -v google-chrome)" > /dev/null 2>&1 || true<</parameters.replace-existing>><<^parameters.replace-existing>>echo "$(google-chrome --version)is already installed to $(which google-chrome)"
                        exit 0<</parameters.replace-existing>>
                      else
                        echo "Google Chrome is not currently installed; installing it"
                      fi
                    fi
                    # install chrome
                    if uname -a | grep Darwin > /dev/null 2>&1; then
                      brew update > /dev/null 2>&1 && \
                        HOMEBREW_NO_AUTO_UPDATE=1 brew cask install google-chrome > /dev/null 2>&1
                      echo -e "#\!/bin/bash\n" > google-chrome
                      perl -i -pe "s|#\\\|#|g" google-chrome
                      echo -e "/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome \"\$@\"" >> google-chrome
                      $SUDO mv google-chrome /usr/local/bin
                      $SUDO chmod +x /usr/local/bin/google-chrome
                      # test/verify installation
                      if google-chrome --version > /dev/null 2>&1; then
                        echo "$(google-chrome --version)has been installed in the /Applications directory"
                        echo "A shortcut has also been created at $(which google-chrome)"
                        exit 0
                      else
                        echo "Something went wrong; Google Chrome could not be installed"
                        exit 1
                      fi
                    elif command -v yum > /dev/null 2>&1; then
                      # download chrome
                      curl --silent --show-error --location --fail --retry 3 \
                        --output google-chrome-stable_current_x86_64.rpm \
                        https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
                      curl --silent --show-error --location --fail --retry 3 \
                        --output liberation-fonts.rpm \
                        http://mirror.centos.org/centos/7/os/x86_64/Packages/liberation-fonts-1.07.2-16.el7.noarch.rpm
                      $SUDO yum localinstall -y liberation-fonts.rpm \
                        > /dev/null 2>&1
                      $SUDO yum localinstall -y google-chrome-stable_current_x86_64.rpm \
                        > /dev/null 2>&1
                      rm -rf google-chrome-stable_current_x86_64.rpm liberation-fonts.rpm
                    else
                      # download chrome
                      echo "installing chrome using ubuntu"
                      curl --silent --show-error --location --fail --retry 3 \
                        --output google-chrome-stable_current_amd64.deb \
                        https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
                      $SUDO apt-get update \
                      > /dev/null 2>&1 && \
                      $SUDO apt-get install -y \
                        apt-utils \
                        fonts-liberation \
                        libappindicator3-1 \
                        libasound2 \
                        libatk-bridge2.0-0 \
                        libatk1.0-0 \
                        libatspi2.0-0 \
                        libcairo2 \
                        libcups2 \
                        libdbus-1-3 \
                        libgdk-pixbuf2.0-0 \
                        libglib2.0-0 \
                        libgtk-3-0 \
                        libnspr4 \
                        libnss3 \
                        libpango-1.0-0 \
                        libpangocairo-1.0-0 \
                        libxcomposite1 \
                        libxcursor1 \
                        libxi6 \
                        libxrandr2 \
                        libxrender1 \
                        libxss1 \
                        libxtst6 \
                        lsb-release \
                        xdg-utils \
                        > /dev/null 2>&1
                      # setup chrome installation
                      $SUDO dpkg -i \
                        google-chrome-stable_current_amd64.deb \
                        > /dev/null 2>&1
                      rm -rf google-chrome-stable_current_amd64.deb
                    fi
                    # test/verify installation
                    $SUDO apt-get -f install
                    if google-chrome --version > /dev/null 2>&1; then
                      echo "$(google-chrome --version) has been installed to $(which google-chrome)"
                    else
                      echo "Something went wrong; Google Chrome could not be installed"
                      exit 1
                    fi
      - browser-tools/install-chromedriver
      - run:
          command: python wms_test.py
          name: wms_test.py

workflows:
  main:
    jobs:
      - build-and-test
